name: Docker Build

on:
  push:
    branches: testMatrix

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tectonic: ["latest", "0.3.1", "0.3.0", "0.1.17", "0.1.12", "0.1.11"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build docker image of tectonic-${{ matrix.tectonic }} and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            dxjoke/tectonic-docker:${{ matrix.tectonic }}-buster-biber