name: Docker Build (Debian)

on:
  push:
    branches:
      - poc_tectonic_with_cache_another
  

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Export Tectonic cache path
        run: echo TECTONIC_CACHE_PATH=$env:LOCALAPPDATA\TectonicProject\Tectonic | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: PHPirates/travis-ci-latex-pdf
      - uses: actions/cache@v2
        name: Tectonic Cache
        id: cache
        with:
          path: ${{ env.TECTONIC_CACHE_PATH }}
          key: ${{ runner.os }}-tectonic-${{ hashFiles('**/*.tex') }}
          restore-keys: |
           ${{ runner.os }}-tectonic-
      - uses: wtfjoke/setup-tectonic@develop
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run Tectonic
        run: tectonic src\main.tex
      - name: Upload pdf
        uses: actions/upload-artifact@v2
        with:
          name: main
          path: src\main.pdf
