name: Docker Build (Debian)

on:
  push:
    branches:
      - poc_tectonic_with_cache
  

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Export Tectonic cache path
        run: echo TECTONIC_CACHE_PATH=$env:LOCALAPPDATA\TectonicProject\Tectonic | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/cache@v2
        name: Tectonic Cache
        id: cache
        with:
          path: ${{ env.TECTONIC_CACHE_PATH }}
          key: ${{ runner.os }}-tectonic-${{ hashFiles('**/*.tex') }}
          restore-keys: |
           ${{ runner.os }}-tectonic-
      - name: Download Tectonic
        run: |
          $client = new-object System.Net.WebClient
          $client.DownloadFile("https://github.com/tectonic-typesetting/tectonic/releases/download/tectonic%400.4.1/tectonic-0.4.1-x86_64-pc-windows-msvc.zip","$pwd\tectonic.zip")
          Expand-Archive -Path tectonic.zip -DestinationPath $pwd
      - name: Run Tectonic
        run: .\tectonic.exe main.tex

